name: trust

dependencies:
  - python=3.9
  - pip
  - pip:
    - pytest
    - bsuite
    - gym
    - gym-minigrid
    - minihack
    - wandb
    - jupyterlab
    - black
    - optax
    - chex
    - rlax
    - flax
    - git+https://github.com/epignatelli/helx#egg=helx
