name: unittests

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        # reproduce environment
        $CONDA/bin/conda env create -f requirements.yml
        # install trust
        $CONDA/envs/trust/bin/pip install -e .
    - name: Test with pytest
      run: |
        $CONDA/envs/trust/bin/pytest
